### PR TITLE
Glatos challenge

### PR DESCRIPTION
**Pull request by SoftwareMonk**

### CODE REVIEW

**Comment by jdpye** [comment]
Some of the comments still refer to Lake Huron, etc etc, but maybe the bounding boxes are good?

**Review by jackVanish — COMMENTED** [review]
Is that PNG supposed to be in the merge? Also in lesson 9 and the corresponding challenge/answers file you say "that bay we zoomed in", but I think it should be "that bay we zoomed in on". Or "that bay on which we zoomed in".

**Review by jdpye — APPROVED** [review]
Just doublecheck the comments to make sure we aren't referring to Huron or any of the other lakes specific stuff (I need to do this, too!)

**Review by naomitress — APPROVED** [review]
code runs without issue, need to review md files once they are in gh-pages and on the web

**Pull request merged**
