### PR TITLE
Minor updates to lesson 7

### PR DESCRIPTION
**Pull request by jackVanish**
Minor additions to the Intro to Glatos lesson. This one was already pretty well laid-out so I didn't have to add much; just some cleanup here and there. One thing, line 154 mentions "location-like" as a way to describe a certain type of column. I don't love this descriptor, I feel like we could have something a little more intuitive, but I don't know enough about what location-like means to supply an alternative. Can someone help me out on that?

### CODE REVIEW

**Review by CaitlinBate — COMMENTED** [review]
generally, this content likely needs to be duplicated for each Node. Maybe a task for @SoftwareMonk 

line 33: when describing where the data is located we should be careful, because I think we will try to use different data for each Node?

line 71: referring to the GLATOS network should be in caps

line 95: maybe describe that we can choose the time-lag threshold?

line 154: "location-like" can be "if you have another column which describes the location of a detection which you'd prefer..." or similar.

**Comment by jackVanish** [comment]
@CaitlinBate Got your changes folded in; I agree we should get this split up for each node but that's probably a different task once we get this repo into its forever home.

**Review by CaitlinBate — APPROVED** [review]
episode 7 -

line 24 directs to the GLATOS data folder, however line 71 suggests we are actually supposed to be using ACT data with this code.

lots of the specifics will have to change once we start duplicating for each node anyway :P

**Comment by jackVanish** [comment]
Good call, as you say it's al gonna be switched once it gets moved into separate lesson plans.

**Pull request merged**
