### PR TITLE
Added a lot of text to flesh out the lesson, and cleaned up some of the code. 

### PR DESCRIPTION
**Pull request by jackVanish**
Big changes to make the lesson a little more text-heavy, as with episode 1. Also some minor code tidying and the conversion of comments to text sections that are a little more instructive for people who are just reading the curriculum rather than attending a workshop.

### CODE REVIEW

**Review by CaitlinBate — COMMENTED** [review]
line 15: ... not unlike tables in typical spreadsheet format (ex: Excel). In R, they are represented as vectors of vectors: that is, a vector wherein each column is itself a vector

line 23: Before we can start analyzing our data, we need to import it into R.

line 86: i think we should still introduce the shortcut for a pipe (ctrl shift m)

line 128: i don't think "take the dataframe output of group_by and condense it to fewer rows, trimming out some of the repeated data" is the most accurate/instructive definition of summarise(). perhaps something like "which can be used to calculate summary statistics across your grouped variables, and produces a new dataframe containing these values as the output"

line 134: #Group the data by catalognumber- that is, create a group within the dataframe where each group contains all the rows related to a specific catalognumber. AND THEN...

line 166: ....use-cases

line 200: your time should be in 24 format  (ex "2021-05-14 14:21:40) for both examples

line 202: ...parse_date_time which can be used

**Comment by jackVanish** [comment]
Thanks for the catch on summarise! I wasn't sure if i was giving quite the right info. Changes made per your suggestions.

**Review by CaitlinBate — APPROVED** [review]

**Comment by CaitlinBate** [comment]
i am now noticing that several of these sections should be repeated (imports/quick summaries/"rbind") showing examples for other network-style extracts. Ex: insert/edit all code from the GLATOS and FACT workshops as well

**Comment by CaitlinBate** [comment]
added code for FACT and GLATOS as well. text should be the same but I welcome a review

**Pull request merged**
