### PR TITLE
Md updates

### PR DESCRIPTION
**Pull request by naomitress**
fixes from https://github.com/ocean-tracking-network/2021-04-13-act-workshop/pulls as well as updates to all day 1 md and some day 1 code

### CODE REVIEW

**Comment by jdpye** [comment]
OK it looks clean to me but i haven't been editing these files. if Bruce is OK with it becoming part of his PR we're good to go here, and then I can re-review the PR that's pointed at gh-pages.

**Review by jdpye — APPROVED** [review]
Good by me, the code doesn't -have- to live in the gh-pages subbranch, and we can remove or update it as we prefer once things are finalized on the code-writing side. We should get Bruce's OK on the PR so he knows what's added to his PR that goes to gh-pages and the website.

**Comment by jackVanish** [comment]
Looks good to me, I'm gonna have to make a couple changes here and there once I get the last of these plots working but that won't be a big deal, I can do that myself. No reason that should be a blocker for anyone needing this merged, it won't substantially change things.

**Review by jackVanish — COMMENTED** [review]
Changes look good to me, let's get 'em in.

**Pull request merged**
